### ISSUE TITLE
[Feature request] : Add Login and Logout Functionality

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#10]
**Feature Request:** 
Currently, our app only has a login and logout button which are not responsive, we would like to introduce a complete login and logout feature.

**Details:** 
The new functionality should include the ability for users to securely log into their accounts and log out when they are done using the app.

**Benefits:** 
Adding this feature will enhance user experience and security, allowing users to have personalised accounts and ensuring that their sessions can be terminated when needed.

**Records:**

- [ ]  Develop the login page with appropriate fields for username/email and password.
- [ ]  Implement user authentication and validation to ensure secure login.
- [ ]  Create a logout button or option accessible to users when they are logged in.
- [ ]  Ensure that the logout process effectively ends the user's session.
- [ ]  Test the login and logout functionality across different devices and browsers to ensure compatibility and security.
- [ ]  Update the app's documentation and user guides to include information about the new login and logout features.

**Additional Information:**

- Contributors interested in working on this feature can reach out for more details and guidance.
- We appreciate your help in making our app more user-friendly and secure!

**Comment by Anandsg** [comment]
@LynxSumit okay! Let's proceed with OAuth as the foundation, and if any additional packages or specific configurations are needed, we can discuss and integrate them as we go along

**Comment by Anandsg** [comment]
Thank you for the interest.

**Comment by Anandsg** [comment]
@LynxSumit That's a good point to consider. Using a Google Sign-In with a PopUp can sometimes affect the clarity of the form. Since I'm primarily a frontend developer and not entirely familiar with backend technologies, I trust your judgment on selecting the backend technology for sign-in/sign-up. Please feel free to proceed with this as you're comfortable with, and I'll be happy to review it after the pull request (PR) is submitted.

**Comment by Anandsg** [comment]
I haven't done any restrictions on library installations. It seems like there might be an issue with the development environment. may i know what is the error you are getting ?

**Comment by Anandsg** [comment]
@LynxSumit I got it why you are getting build error can you try to run below command and see.

npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9

**Comment by Anandsg** [comment]
I see, can you try to fork the latest merge commit version i have just updated the repo. Not sure for others it is working fine and they’re fine with that

**Comment by Shahidkhatrii** [comment]
Hi @Anandsg I would like to work on this issue

**Comment by Anandsg** [comment]
Hey! @LynxSumit the developer @Shahidkhatrii is ready to work on this. Can you please confirm if you're still having trouble installing libraries, or if you've already started working on the feature? If not, we can add this task to @Shahidkhatrii 's to-do list.

**Comment by Anandsg** [comment]
@LynxSumit Thank you so much! Feel free to choose another feature or issue when you're ready.
@Shahidkhatrii assigning the issue to your bucket under hacktoberfest You can use any backend technology or libraries you're comfortable with. Our main goal is to implement straightforward login/logout functionality.

**Comment by Anandsg** [comment]
As I'm not familiar with the backend tech stack and haven't developed such features before, it would be great if you could use your own styling/design that suits the app's best. I'll assign this issue to some backend developer for a code review once you're done (if needed i will review it).

**Comment by Shahidkhatrii** [comment]
Hi @Anandsg I have implemented the login functionality using oauth which uses google account for authorization.

**Comment by Anandsg** [comment]
@Shahidkhatrii Great to hear that, would it be possible to make a PR or you have any concerns that needs to be discussed before that?

**Comment by Shahidkhatrii** [comment]
yes I had to tell you that for using oauth we have to provide Client ID so I tested the functionality using my google account client id and I am making PR without that client id so you can provide it from your end.

![Screenshot 2023-10-03 215321](https://github.com/Anandsg/Hungry-hero/assets/104732343/c0a7e81a-5265-4a3f-83bc-6c05fdcf8ede)

**Comment by Anandsg** [comment]
@Shahidkhatrii yeah that make sense, i will update it
