### ISSUE TITLE
Align search bar to center for md size 

### ISSUE THREAD

**Issue by ThennarasuTW** [Anandsg/Hungry-hero#101]
The search bar has 96px of left padding. This breaks the alignment of search bar in `md` size screen.
I'm implementing the following design,

- For size `lg` , the search bar will be aligned left with 96px padding left
- For size `md`, the search bar will be aligned center
- For size `sm`, the search bar will be aligned center

Please assign this issue to me, thanks.

<img width="998" alt="Screenshot 2023-10-07 at 1 34 26 PM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/4df1ddac-b738-49b4-ac47-0476978cf516">

**Comment by Anandsg** [comment]
Make sense please go for it @ThennarasuTW
