### ISSUE TITLE
Change card background-color and transition

### ISSUE THREAD

**Issue by tsongtheng** [Anandsg/Hungry-hero#106]
The card background-color and app background-color is same. It doesn't look good. Can i change it?
Also, there is no transition effect while hovering the card. Can i change this too?

**Comment by tsongtheng** [comment]
Please assign me if you  want them to change.

**Comment by Anandsg** [comment]
I don't think changing the background color is a good idea for this app. anyway I'll assign the issue to you, and please try to come up with a better design so that I can take a look at the changes and review them.

**Comment by tsongtheng** [comment]
Should i make it look like swiggy?  In swiggy the card scale down when hovered.

**Comment by Anandsg** [comment]
@tsongtheng You can try both approaches and see for yourself which one looks better. If both effects look good, you can go ahead and implement them further.

**Comment by tsongtheng** [comment]
Hi @Anandsg, can you tell me how to run this project after cloning to to my local device. I have run `npm install` and then `npm start`. But I'm  stuck here
```
[tipchan_s@archlinux Hungry-hero]$ npm start

> namaste-react@1.0.0 start
> parcel index.html

Server running at http://localhost:1234 
⠋ Building...egrep: warning: egrep is obsolescent; using grep -E
✨  Built in 5.76s.
```

**Comment by Anandsg** [comment]
run below host server in ur local

http://localhost:1234

**Comment by tsongtheng** [comment]
Ok, thank you.

**Comment by utkarshtenguriya** [comment]
Hey I will like to work on this issue @tsongtheng

**Comment by tsongtheng** [comment]
Hello @utkarshtenguriya, I am already working on this issue.
