### ISSUE TITLE
Fix favourite button

### ISSUE THREAD

**Issue by ThennarasuTW** [Anandsg/Hungry-hero#117]
Currently the favourite button doesn't turn red on click.
Also since the button color is black, it doesn't standout on black backgrounds.
After the fix, when the button is clicked and turned red, it doesn't standout on red backgrounds.
<img width="928" alt="Screenshot 2023-10-08 at 1 36 09 PM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/5d34ba65-0e93-4819-af2a-55169cc23655">

I suggest we add a white outline on the button like the following,
Preview for black backgrounds
<img width="310" alt="Screenshot 2023-10-08 at 1 35 20 PM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/98a30c56-79c9-49d9-beaa-7f85c02fe61d">

Preview for red backgrounds (After it is selected as favourite)
<img width="310" alt="Screenshot 2023-10-08 at 1 35 13 PM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/c265a0a7-730c-48aa-93a4-5a4535206be4">

Preview for white backgrounds
<img width="310" alt="Screenshot 2023-10-08 at 1 35 34 PM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/11c11eba-4123-436c-a131-701a2e104b1c">

So, as part of this issue,
I will

- [x] Fix the favourite button
- [x] Add white outline to the favourite button

Please assign me this issue if its valid. Thanks.

**Comment by Anandsg** [comment]
Go ahead brother
