### ISSUE TITLE
Dynamic circular border for scroll

### ISSUE THREAD

**Issue by SrishtiSonam** [Anandsg/Hungry-hero#122]
Enhance the existing scroll-to-top button by implementing a dynamic colored border that gradually transforms into a full circle while the page is scrolled downward.
Create a design like the image below but customized for this website.
<img width="122" alt="image" src="https://github.com/Anandsg/Hungry-hero/assets/113123593/275d5f5c-2d34-4398-936f-820ac434d1f4">
Could you please consider assigning me to this task as part of Hacktoberfest if it meets your requirements for this project?

**Comment by Anandsg** [comment]
make sense @SrishtiSonam Go ahead

**Comment by SrishtiSonam** [comment]
Thank you assigning this task to me. I will provide you with an update by the end of this week.

**Comment by prakhar1535** [comment]
I HAVE ADDED A PR REGARDING THIS ISSUE KINDLY CHECK.

https://github.com/Anandsg/Hungry-hero/assets/113304996/880fcbd8-f188-4557-9a5b-1eb016633cfe
