### ISSUE TITLE
Inconsistent font families

### ISSUE THREAD

**Issue by ThennarasuTW** [Anandsg/Hungry-hero#126]
I can see two different font styles were used in the application.
Is this intentional? If not I can work on fixing this. Thanks.
<img width="1695" alt="Screenshot 2023-10-09 at 10 09 07 AM" src="https://github.com/Anandsg/Hungry-hero/assets/77829767/b7446ce9-3a09-4b52-a29c-3eee002fda79">

**Comment by Anandsg** [comment]
it is not intentional since these two different fonts looks good on the web page we kept as it is, if you have good approach and designing skills you can use and make it more attractive with different fonts

**Comment by ThennarasuTW** [comment]
@Anandsg , I have usually seen the same font used everywhere in web applications. I thought of using the font family in the `restaurant cards` everywhere. So, we have one font family used everywhere. Please let me know what you think. Thanks.

**Comment by Anandsg** [comment]
okay go ahead
