### ISSUE TITLE
Cart-Item card buttons alignment mismatch

### ISSUE THREAD

**Issue by webdev-vignesh** [Anandsg/Hungry-hero#127]
**Description:**

In the Cart section of the page we can see the items added to our cart, where the buttons like **Increment(+)**, **Decrement(-)** and **Delete(X)** are not in the same alignment. 

![Buttons-misalign](https://github.com/Anandsg/Hungry-hero/assets/108517094/5c66350a-4dea-49e8-b69d-df2c095873fc)

![Delete-button-overlap](https://github.com/Anandsg/Hungry-hero/assets/108517094/97b0bcd7-af6e-4191-9cfa-574bcc66b404)

The **Delete(X)** button is also touching the bottom-right ends of the card when we hover on it which affects UI/UX. 
It is because of the reason **Delete(X)** button is given CSS properties of ```absolute bottom-0 right-0``` whereas **Increment(+)** and **Decrement(-)** are inside another element.

**Proposed Changes:**
* All 3 buttons can be nested inside the same element.
* Flexbox can be used to distinguish (Increment, Decrement) and Delete buttons in the same alignment.

**Comment by Anandsg** [comment]
Make sense would you like to address the issue ?

**Comment by webdev-vignesh** [comment]
Yes @Anandsg 
Can you please assign me to this issue and add Hacktoberfest labels.

Thanks in advance!
