### ISSUE TITLE
[Enhancement] : Menu Screen UI enhancement

### ISSUE THREAD

**Issue by ChammounC** [Anandsg/Hungry-hero#138]
## Summary:
 Currently, when users access the menu section, it looks empty. There's data available in the API that we can use to fill the blank spaces.

![Screenshot 2023-10-09 231019](https://github.com/Anandsg/Hungry-hero/assets/43007452/ee9dffa1-7e9d-4690-9ab0-f8a12762ebfd)

## Proposed Enhancement:
 I'm thinking of changing that section to this. This should enhance the look and user experience.

![Screenshot 2023-10-09 231330](https://github.com/Anandsg/Hungry-hero/assets/43007452/8ab783ae-7c69-4dd7-baac-9b22248db2b2)

**Comment by prakhar1535** [comment]
i want to work in this issue please assign if possible

**Comment by Anandsg** [comment]
@ChammounC Good idea yes we have all the data available in the API, would you like to work on it?

**Comment by ChammounC** [comment]
@Anandsg yes.

**Comment by Anandsg** [comment]
Assigned the issue.
