### ISSUE TITLE
[Enhancement] Appearance of Navbar for great User Experience

### ISSUE THREAD

**Issue by JatinBawne** [Anandsg/Hungry-hero#144]
The buttons (hyperlinks) in the nambar should have more gap among them to enhance the first view of the webpage.

Also there should be a heading "HUNGRY HERO" in the navbar next to the 'Hungry Hero' icon to make it more striking.

<img width="1346" alt="Screenshot 2023-10-10 at 8 40 54 PM" src="https://github.com/Anandsg/Hungry-hero/assets/99788083/6e8eadbe-336e-4b53-931a-0a7345688059">

**Comment by JatinBawne** [comment]
@Anandsg kindly assign this issue to me, will fix this in no time.

**Comment by JatinBawne** [comment]
I've setup the repo in my local machine, but after editing the code, changes are not reflecting in web page.
@Anandsg kindly help.

https://github.com/Anandsg/Hungry-hero/assets/99788083/6d3dc754-8606-4a48-a230-724acca0bc46

**Comment by Krish-Panchani** [comment]
@Anandsg  I can fix this, also have experience with Tailwind CSS, can you assign me this issue?
