### ISSUE TITLE
image and text content is just too close to each other, not good for ux

### ISSUE THREAD

**Issue by nishant3721** [Anandsg/Hungry-hero#145]
![image](https://github.com/Anandsg/Hungry-hero/assets/76558924/90f0805a-07b6-4b9b-8d14-fcf55719ae60)

the image and the text content is just too close to each other and need to be refactored for the good user experience.

**Comment by nishant3721** [comment]
I would like to work on this issue!

**Comment by Anandsg** [comment]
Go ahead

**Comment by Niraj-1729** [comment]
I believe that I can make a meaningful contribution by addressing this issue. I have experience in Frontend development and I have worked on various projects. I am eager to work on this specific problem.
Kindly assign this to me !!

THANKS for your consideration.

**Comment by Anandsg** [comment]
@Niraj-1729 Go ahead bro, u can create a PR if the approach is good i will merge the req
