### ISSUE TITLE
Form validation error in Contact US page

### ISSUE THREAD

**Issue by Umang070** [Anandsg/Hungry-hero#152]
![image](https://github.com/Anandsg/Hungry-hero/assets/65073407/ac39c6e5-1a0b-4075-8289-6a97a3fb8808)
I filled out the form cleared it then submitted it again but without filling in the required information application said we would get back to you as you can see in the image. At the time visiting the contact us page before filling in any information, it shows the error messages like enter a valid email address but it should show after the user fills in the information. I would like to work on this issue and fix all these problems.

**Comment by Anandsg** [comment]
Go for it

**Comment by Sha1kh4** [comment]
Please assign.
