### ISSUE TITLE
The Search Restaurants function is not dynamic

### ISSUE THREAD

**Issue by Villain45** [Anandsg/Hungry-hero#158]
the responses of the restaurant search are only displayed when search button is clicked, i want to make this search dynamic so that whenever the user inputs a letter the restaurants of the matching input should be displayed

I want to work on this issue under hacktoberfest

**Comment by Anandsg** [comment]
@Villain45 this make sense please go ahead it

**Comment by Villain45** [comment]
@Anandsg and also when the fav option is selected, the search function works considering all the restaurants options to obtain result instead it should only work for restaurants which are marked as fav right?

**Comment by Anandsg** [comment]
@Villain45 yup, i observed that issue you can go ahead with making the search functionality dynamically i will create another issue for this favourite search issue.

**Comment by Villain45** [comment]
@Anandsg Ok, will work on that after this

**Comment by Villain45** [comment]
@Anandsg what about fav search issue
Can you create a PR and assign me then?

**Comment by Anandsg** [comment]
@Villain45 i have created separate issue for it please check
