### ISSUE TITLE
CORS Error is there while fetching data on Main Section.

### ISSUE THREAD

**Issue by LynxSumit** [Anandsg/Hungry-hero#16]
![Screenshot 2023-10-01 153001](https://github.com/Anandsg/Hungry-hero/assets/114245865/fbb0da73-b968-4316-a094-4813f9772c54)

I think this is a major issue cuz starters and newcomers wont be able to see anything.

**Comment by Anandsg** [comment]
@LynxSumit yes it is expected, have you installed CORS extension from chrome? please install and try sometime browser wont allow us to fetch API's from external sites

**Comment by Anandsg** [comment]
@LynxSumit Hope you're able to access the site now? are we good to close this issue

**Comment by Anandsg** [comment]
sure i will review once you made PR
