### ISSUE TITLE
[Enhancement]: Navbar can be fixed on top

### ISSUE THREAD

**Issue by NilanjanPramanik** [Anandsg/Hungry-hero#160]
Hey I feel that the Navbar could be fixed at the top . It would be very much convenient for the user. I want to work on the feature. Can I start ?

**Comment by Anandsg** [comment]
can you elaborate the issue with current nav bar? i see Nav bar looks great in middle of the header, are you saying instead of middle you will fix them at top?

**Comment by Anandsg** [comment]
Got it you will fix the header at same place ?

**Comment by NilanjanPramanik** [comment]
Yesh
![Screenshot 2023-10-11 213808](https://github.com/Anandsg/Hungry-hero/assets/121485018/aa080087-44e5-4840-bc87-c2391ee47892)

after you scroll the navposition is not fixed 

![Screenshot 2023-10-11 213815](https://github.com/Anandsg/Hungry-hero/assets/121485018/402fc073-323d-4caa-a07f-d00900251d3d)

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg  I have an idea if you allow me i can work on that

**Comment by Anandsg** [comment]
Got it, go ahead with the changes

**Comment by NilanjanPramanik** [comment]
@Anandsg  Thanks you. can the issue got labeled hacktobarfest if you don't mind

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg I am attaching some photos can you please review it.
For large screen 
![Screenshot 2023-10-11 223859](https://github.com/Anandsg/Hungry-hero/assets/121485018/3342effd-c77e-4e49-9926-3df3ce99e8d1)

For mobile screen
![Screenshot 2023-10-11 223931](https://github.com/Anandsg/Hungry-hero/assets/121485018/5f248593-1dd5-4f71-892e-ce8433dfcea2)

**Comment by Anandsg** [comment]
Looks good please create PR i will review and let u know if any further changes required

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg I have created the PR please review it
