### ISSUE TITLE
Add Meta tags like Open Graphs & Description Tags.

### ISSUE THREAD

**Issue by Krish-Panchani** [Anandsg/Hungry-hero#163]
Open Graph meta tags are helps to control how URLs are displayed when shared on social media and preview your webpage whenever someone shares your link.

**Comment by Krish-Panchani** [comment]
Assign me if like this. I can add that tags.

**Comment by Anandsg** [comment]
Go ahead @Krish-Panchani

**Comment by Krish-Panchani** [comment]
@Anandsg I have question about Logo path.
If I add "https://hungry-hero-ag.netlify.app/src/assets/logo.png" as path will that works?

**Comment by Krish-Panchani** [comment]
![image](https://github.com/Anandsg/Hungry-hero/assets/74005086/19af4414-5cfc-488c-b00f-5a377e9af3e9)

like this
