### ISSUE TITLE
Moving from absolute paths to relative paths

### ISSUE THREAD

**Issue by BharatSharma29** [Anandsg/Hungry-hero#166]
We are still setting absolute path as the value for the path attribute. But in future, as the app grows it will become tedious and will be more nested making it unmaintainable. So, I think that moving towards relative paths will make it better.

Please assign me this under hacktoberfest thank you.

**Comment by BharatSharma29** [comment]
Hi @Anandsg my PR for issue #165 has not been merged yet. And I want to resolve the above issue in the code changes that I made in PR for #165 issue. Can you please merge it. If there's a problem with it do let me know.

**Comment by Anandsg** [comment]
your PR has been merged
