### ISSUE TITLE
Profile Component not showing up

### ISSUE THREAD

**Issue by BharatSharma29** [Anandsg/Hungry-hero#167]
We are not using <Outlet /> inside the <About /> component. That's why when we route to "/About" the profile component won't show up. I would like to resolve this issue do assign me this

**Comment by Anandsg** [comment]
Okay go for it @BharatSharma29

**Comment by BharatSharma29** [comment]
> Okay go for it @BharatSharma29

Hi @Anandsg I saw the Profile component and it is incomplete. What was your initial idea behind it? and what did you wanted to do with it? can you please elaborate on that to me so I will have a better understanding of it.

**Comment by Anandsg** [comment]
hey @BharatSharma29 It was just a dummy component I created during practice to understand the difference between functional components and class-based components. I forgot to clean up the code afterward. I believe we can safely remove the profile component from the application, as well as the route reference to it in the app.js component.

**Comment by BharatSharma29** [comment]
Okay let me create an issue for it then

**Comment by Anandsg** [comment]
Cool, i will go ahead and close this issue
