### ISSUE TITLE
Body is empty on page load

### ISSUE THREAD

**Issue by koyaboy** [Anandsg/Hungry-hero#168]
Decided to try out the app to see what I can contribute but on page load there was no data showing up. The body was completely blank

Assign me this issue under hacktoberfest and allow me to figure it out

**Comment by Anandsg** [comment]
We are using live API and occasionally, there might be a delay in getting the data, which is why you'll see a shimmer effect for a brief moment.

**Comment by koyaboy** [comment]
For me nothing showed up @Anandsg . I checked the console and there was an issue

**Comment by Anandsg** [comment]
can you share the screenshot
