### ISSUE TITLE
[Bug report] : Item removal button Overlaps description in Cart

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#169]
**Issue Description:**
When a user adds only one item to the cart or adds multiple items and starts removing them until only one item remains, the "Remove" button overlaps with the description of the item. Additionally, there is a conflict between the item description's border-bottom and its size, particularly when the item description is small.

**Expected Behaviuor:**
The "Remove" button should be properly aligned and not overlap with the item description. The border-bottom of the item description should also display correctly, regardless of the description's size.

<img width="1320" alt="Screenshot 2023-10-12 at 8 35 30 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/cc7fad72-5716-445c-b1d6-629110a3787a">

**Comment by Rahul-Roy-Hub** [comment]
I will do that assign me.

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue can you assign me this?

**Comment by RajaVardhan-coder** [comment]
@Anandsg I am ready with the code can you assign this to me
<img width="1440" alt="Screenshot 2023-10-12 at 10 21 17 AM" src="https://github.com/Anandsg/Hungry-hero/assets/69043917/6b324515-88d7-477d-9d63-1e1719980abf">

**Comment by Anandsg** [comment]
@RajaVardhan-coder Please create a PR

**Comment by RajaVardhan-coder** [comment]
> @RajaVardhan-coder Please create a PR

Done

**Comment by Rahul-Roy-Hub** [comment]
@RajaVardhan-coder It looks good but also give Remove Button Background Orange to look better Ui.

**Comment by RajaVardhan-coder** [comment]
@Rahul-Roy-Hub Good idea

<img width="1440" alt="Screenshot 2023-10-12 at 1 46 25 PM" src="https://github.com/Anandsg/Hungry-hero/assets/69043917/ed42b8cb-1f5c-4561-a3cb-52750e852b7a">

**Comment by RajaVardhan-coder** [comment]
@Anandsg can you please check my pull request

**Comment by Anandsg** [comment]
Sure @RajaVardhan-coder
