### ISSUE TITLE
Contact Us Form Validation error showing before any input

### ISSUE THREAD

**Issue by Arbtrage** [Anandsg/Hungry-hero#172]
<img width="312" alt="image" src="https://github.com/Anandsg/Hungry-hero/assets/100552235/8de903a2-bd7c-44a9-b1af-b78aff927648">

Before entering anything the form, it already shows the validation errors.
In the Contact.js file the `nameError` hook could be modified to have initial value as false and when the user starts typing it would be true. So that it effectively shows the error message when needed  and not always.

Would like to work on this issue, please assign me this @Anandsg .

**Comment by Adi-21** [comment]
I have solved this issue , Can I generate a PR for this issue #172

**Comment by Anandsg** [comment]
@Adi-21 sure

**Comment by Arbtrage** [comment]
Isn't it a best practice to assign the issue to the one who has created/ asked to work on it first ? @Anandsg

**Comment by Adi-21** [comment]
ya ok that's great but if no one is there to solve , I would love to have a look to my PR

**Comment by Anandsg** [comment]
@Arbtrage Someone else reported this issue yesterday, and it has already been fixed. Check the closed issues to see if you're referring to something different let me know if you're trying to say something different than the one is closed
