### ISSUE TITLE
Enhancement of NavLinks 

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Anandsg/Hungry-hero#175]
It would be great to highlight the active link in the navbar based on the page we are currently viewing.

**Screenshot of the current behavior:**
All pages have the same color for the link in the navbar.
![image](https://github.com/Anandsg/Hungry-hero/assets/102857774/0765db61-b131-4d6a-9652-62747d88a127)

**Screenshot of the desired improved behavior:**
When viewing the Home page, the active link should appear as follows:
![image](https://github.com/Anandsg/Hungry-hero/assets/102857774/93a4a9e5-a640-4c57-a580-53fe2c82767a)
When viewing the About page, the active link should appear as follows:
![image](https://github.com/Anandsg/Hungry-hero/assets/102857774/618ee417-7009-4979-b756-a675b5194d41)

I would like to work on this.

**Comment by Niraj-1729** [comment]
Hey , I can work on this issues !! 
Kindly assign this to me
