### ISSUE TITLE
Navbar Animation

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Anandsg/Hungry-hero#179]
At present, the navbar is sticky and doesn't move, but an animation has been added to make it visible when the user scrolls up. This enhancement will add more UI to the user experience. However, when the user scrolls down, the navbar remains hidden. 

Please watch the video below for a clearer demonstration.

https://github.com/Anandsg/Hungry-hero/assets/102857774/fbf5520d-1160-487f-a1ad-0d7272784f85

If you like this animation, I'll create a pull request for this issue.

**Comment by Anandsg** [comment]
Yeah, this improvement enhances the user experience. However, I wish we could make the header/navigation bar stay in the same place, similar to Swiggy. That would be a great feature and make it even more user-friendly. What are your thoughts on this

**Comment by Pinaka-Pani-18** [comment]
Like this right?
https://github.com/Anandsg/Hungry-hero/assets/102857774/a5323b89-8b7d-4c4c-8210-a162f0c632cc

**Comment by Pinaka-Pani-18** [comment]
> Yeah, this improvement enhances the user experience. However, I wish we could make the header/navigation bar stay in the same place, similar to Swiggy. That would be a great feature and make it even more user-friendly. What are your thoughts on this

I prefer the first one because of the animation, but it's your choice. What can I do?

**Comment by Anandsg** [comment]
@Pinaka-Pani-18 I would suggest you to go with second feature fixing the nav bar

**Comment by Pinaka-Pani-18** [comment]
> @Pinaka-Pani-18 I would suggest you to go with second feature fixing the navbar

Okay, @Anandsg, should I fix only the navbar, or should I also fix both navbar & search ?

**Comment by Anandsg** [comment]
Nav bar is enough
