### ISSUE TITLE
[ENHANCEMENT] Adding Text Logo next to brand Logo in Navbar

### ISSUE THREAD

**Issue by JatinBawne** [Anandsg/Hungry-hero#181]
Adding Text Logo next to Brand Logo in navbar may enhance the overall look of the web page.

kindly review this image and suggest change(s) if needed.

<img width="1438" alt="Screenshot 2023-10-12 at 7 46 10 PM" src="https://github.com/Anandsg/Hungry-hero/assets/99788083/a5503ab0-a81d-4b17-97a2-a39e41f8f0bd">

**Comment by JatinBawne** [comment]
@Anandsg kindly assign this isse to me.

**Comment by Anandsg** [comment]
@JatinBawne we had similar feature a few days back since this title not looking that much great on this web app i reverted the changes feel free to pick other issues
