### ISSUE TITLE
[Bug report] : Inconsistent error messages for Nonexistent Favourites

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#182]
**Issue Description:**
When a user adds items to their favourites list, then views their favourite list and searches for an item that doesn't exist in the favourites, they encounter two error messages. This inconsistency in error messaging is not providing a good user experience.

**Proposed Solution:**
Upon searching for a restaurant that doesn't exist in the favorites list, the user should receive a single error message, which reads: "The restaurant you're searching for doesn't exist." Additionally, a "Go back to home" button should be displayed as an option to easily navigate back to the homepage.
<img width="810" alt="Screenshot 2023-10-12 at 9 34 11 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/0c6a6855-dcfc-43a6-bce5-d85e8530c75d">

**Comment by Villain45** [comment]
Can I work on this thing?

**Comment by Anandsg** [comment]
@Villain45 sure go for it

**Comment by Villain45** [comment]
@Anandsg is this issue taken up by someone?

**Comment by Anandsg** [comment]
@Villain45 No u can work on it
