### ISSUE TITLE
[feat]: Input focus functionality for enhancing user experience

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [Anandsg/Hungry-hero#198]
Hi @Anandsg 

i have added the focus functionality for the input field, this enhance the user experience.

**Focus functionality:** As the application loads, the focus functionality in the search bar starts blinking. so that the user can understand to search the required food recipe.

Please refer the video : [Input focus functionality](https://drive.google.com/file/d/1WaCNyDdVLaukIO_Xzq1PlIsCljCcqjF_/view?usp=sharing)

Shall i create a PR ?

**Comment by Anandsg** [comment]
@Prakash-Ravichandran sure let me review

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me too? @Anandsg

**Comment by Prakash-Ravichandran** [comment]
> Can you assign this to me too? @TheShiveshNetwork 

i was working on this

**Comment by TheShiveshNetwork** [comment]
> > Can you assign this to me too? @TheShiveshNetwork
> 
> i was working on this

Alright mate, np
