### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by Gururajraibagi** [Anandsg/Hungry-hero#2]
Due to the fact that we are hitting the Swiggy API, we get a CORS error when loading the page

![image](https://github.com/Anandsg/Hungry-hero/assets/25153717/9cbc5f71-b89e-4c6a-9ba5-2de03ab68b87)

**Comment by Anandsg** [comment]
Please install the CORS extension for chrome and try, as we are using live swiggy API the browser doesn't allow to fetch data from external site. please install CORS from below link and revert back for any further issue

https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

<img width="1199" alt="Screenshot 2023-09-21 at 8 16 53 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/2f5b3662-802c-41d2-b1ed-a8a693a0ceb1">

**Comment by Gururajraibagi** [comment]
Working fine after installing the extension thank you.
