### ISSUE TITLE
i couldn't able see the input search bar after pushing & pulling new changes.

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [Anandsg/Hungry-hero#201]
@Anandsg 

What's the issue ?

I couldn't able see the search bar.

i want to integrate issue #198, please revert the changes, so that i can push the commits for focus input.

![image](https://github.com/Anandsg/Hungry-hero/assets/74542543/d5ebeb0a-8051-45a9-a2f4-2f2c128b1229)

**Comment by Anandsg** [comment]
I can clearly se search box feature with the lastest changes, please pick other issues

<img width="1342" alt="Screenshot 2023-10-13 at 9 36 36 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/1dba0f20-337a-4793-ad48-9aae1e33ed06">

**Comment by Prakash-Ravichandran** [comment]
@Anandsg 

please see in live link - [live link](https://hungry-hero-ag.netlify.app/)

![image](https://github.com/Anandsg/Hungry-hero/assets/74542543/0bb29973-3632-48ac-bd04-963071e12a46)

**Comment by Anandsg** [comment]
> live link

See below screenshot with live link :
<img width="1422" alt="Screenshot 2023-10-14 at 8 12 07 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/dac3f67e-5db4-4e7f-9df9-56981aa98562">
