### ISSUE TITLE
Styling buttons

### ISSUE THREAD

**Issue by harshsbhandari** [Anandsg/Hungry-hero#210]
making the search button same as rating and favourite buttons
![Screenshot (152)](https://github.com/Anandsg/Hungry-hero/assets/73375087/a0f833de-0d9b-4b4e-8107-a949a9d3c49a)

**Comment by Karan-Palan** [comment]
I'd like to work on this

**Comment by MrDBC** [comment]
why this issue isnt closed yet? @Anandsg

**Comment by Anandsg** [comment]
closed now @MrDBC
