### ISSUE TITLE
[Bug report] : Prevent page reload when navigating from "empty favourites page"

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#215]
Issue Description:
When a user goes to their favourites and finds no favourite items, they have the option to click on the "Find your favourite restaurants now" arrow, which should take them to the home page. However, the problem is that clicking on this arrow triggers a page reload. This page reload is unnecessary and can be a suboptimal user experience.

Expected Behavior:
When the user clicks on the "Find your favourite restaurants now" arrow from the empty favorites page, the application should navigate to the home page without triggering a full page reload.

<img width="1277" alt="Screenshot 2023-10-14 at 5 22 55 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/559fe4c9-f08e-4eb3-8191-6754d56d1245">

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by NilanjanPramanik** [comment]
Hey @Anandsg  can i start working on this issue

**Comment by NilanjanPramanik** [comment]
@Anandsg can I make a new end point for the favourite like /favourite

**Comment by Anandsg** [comment]
@NilanjanPramanik No please, i'd like to give opportunity to some other developers you already made enough contribution here

**Comment by Anandsg** [comment]
@hemanth110702 start working on this

**Comment by NilanjanPramanik** [comment]
Yeah... Absolutely...

**Comment by apurvagurme** [comment]
Hi @Anandsg, can I also start working on this issue?

**Comment by Anandsg** [comment]
Sure you can @apurvagurme

**Comment by MrDBC** [comment]
@Anandsg  can I work on this issue?

**Comment by apurvagurme** [comment]
@Anandsg I have fixed it and raised a PR please look into it https://github.com/Anandsg/Hungry-hero/pull/223
