### ISSUE TITLE
[Bug report] : remove unnecessary "Arrow" symbol on clearing search Input

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#216]
Issue Description:
When a user performs a search for a restaurant, a dynamic search bar is built, and search results quickly appear. However, a problem arises when the user clears the search input. An "Arrow" symbol appears as an indication of the cleared search, but even after clearing the input and returning to the home page, this "Arrow" symbol persists on the page, which is unnecessary.

Expected Behavior:
Upon clearing the search input and returning to the home page, any unnecessary symbols or elements, such as the "Arrow," should be removed, providing a clean and uncluttered user experience.

Refer below screenshots:
<img width="1317" alt="Screenshot 2023-10-14 at 5 33 19 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/24552e1b-6c43-4145-a398-5fcc010a5766">

<img width="1348" alt="Screenshot 2023-10-14 at 5 33 48 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/475074ed-5d23-47f3-9dff-1715f693b9f7">

**Comment by Petsamuel** [comment]
assign to me

**Comment by Anandsg** [comment]
Assigned the issue
