### ISSUE TITLE
Enhance "No Favourites Found" user experience with an image

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#217]
Issue Description:
Currently, when there are no favourites found, the application displays the message "Find your favorite restaurants now" followed by an image. However, the existing image may not be very user-friendly or aesthetically pleasing. This can impact the overall user experience.

Expected Behavior:
We should enhance the user experience by replacing the existing image with a more visually appealing and user-friendly one when there are no favorites found. A well-chosen image can contribute to a better user interface and convey a more positive message.
<img width="974" alt="Screenshot 2023-10-14 at 5 38 49 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/bae875c2-237a-466c-bad9-30465d2a00ed">

**Comment by TheShiveshNetwork** [comment]
Assign me this, I'll be working on this one @Anandsg

**Comment by Anandsg** [comment]
@TheShiveshNetwork Go ahead

**Comment by MrDBC** [comment]
cAN I WORK ON THIS? @Anandsg

**Comment by TheShiveshNetwork** [comment]
@Anandsg check out #230
