### ISSUE TITLE
[feat]: Sequential focus functionality for contact component

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [Anandsg/Hungry-hero#221]
@Anandsg 

I have worked on improving the user experience in the contact component.

For this PR, Our contact component sets the focus for next,next input on pressing the enter key.

Please refer this video [Contact Component Sequential Focus](https://drive.google.com/file/d/1Zih0yVcCh6JhX3y7F7lPc5gY4iUz3jov/view?usp=sharing)

(In the video i will press enter as soon as i finished entering the inputs)

Can you assign this to me ? 

Will create a PR now, as it is mergeable.

**Comment by Anandsg** [comment]
create a PR will review the changes
