### ISSUE TITLE
[feature ] : Making footer responsive across all the pages

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#224]
**Description:**
The current footer on our website is not responsive across all pages, which impacts the overall user experience. We need to make sure that the footer adapts to different screen sizes and remains user-friendly.

<img width="623" alt="Screenshot 2023-10-14 at 8 57 46 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/25fbb9de-6ebf-4f51-a161-20d30ff0ec40">

**Comment by beatrizsmerino** [comment]
Hello !!
I want participate, Can you assign me the task?

**Comment by Anandsg** [comment]
Please go ahead @beatrizsmerino

**Comment by beatrizsmerino** [comment]
> Please go ahead @beatrizsmerino

thank you very much, I'm going to do it 😊

**Comment by beatrizsmerino** [comment]
thank you for the opportunity @Anandsg
You can see the fix at PR: https://github.com/Anandsg/Hungry-hero/pull/227
