### ISSUE TITLE
 Improve User-Friendly Error Message for Nonexistent Search Results

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#229]
Problem:
Currently, when a user searches for items that do not exist, we display a generic error message. This error message doesn't provide a positive user experience and can leave users feeling frustrated or lost.

Suggested Improvement:
We should enhance the user experience by providing a more user-friendly error message along with a relevant image. This will help users understand the situation better and guide them towards a solution or alternative action.
<img width="954" alt="Screenshot 2023-10-14 at 10 40 25 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/cf4f9f5d-d4ce-42ec-8d1a-2e0a007b5f52">

**Comment by mit-anuj** [comment]
please assign me this issue . I will do my best to generate PR as soon as possible

**Comment by bhanuteja-03** [comment]
I am interested to work on this issue. Please assign me

**Comment by TheShiveshNetwork** [comment]
Assign this to me @Anandsg

**Comment by ArnavK-09** [comment]
What abt this? ![undraw_online_groceries_a02y.png](https://github.com/Anandsg/Hungry-hero/assets/69188140/41a3b014-4721-4aba-8097-0dfa21198568)
