### ISSUE TITLE
[Bug report] : Prevent page reload when navigating from "non existing items"

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#232]
Issue Description:
When a user inputs the item name that doesn't exists we say message and gave Go back to home button However, the problem is that clicking on this button triggers a page reload. This page reload is unnecessary and can be a suboptimal user experience.

Expected Behavior:
When the user clicks on the "Go back to home" button from error page, the application should navigate to the home page without triggering a full page reload.
<img width="837" alt="Screenshot 2023-10-15 at 12 37 53 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/ba0f0423-8b66-4a9e-a48f-f569c7832577">

**Comment by furqanindikar** [comment]
I can solve this assign me this issue

**Comment by furqanindikar** [comment]
Solved the assigned issue. Also please create a new issue:
In the same state mentioned the Home link in the navbar also does not work P.s (it works but the state of the page remains same)
