### ISSUE TITLE
[Refactor]: Replace Input with material UI's Text field & other props refactoring 

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [Anandsg/Hungry-hero#234]
@Anandsg 

As we have material-ui dependency in the project, shall i refactor all the contact form component input with TextField in the Material-UI.

Adavantages:

1. Enhanced UI Design
2. Easy form controls intergration will be easier on adding material-UI.

Sample Image:

![image](https://github.com/Anandsg/Hungry-hero/assets/74542543/3991acc9-ee97-4402-b4ea-922567423eed)

**Comment by r0ld3x** [comment]
@Anandsg  assign me

**Comment by Prakash-Ravichandran** [comment]
> @r0ld3x 

Please ask for new issue. I am currently working on this.

**Comment by r0ld3x** [comment]
@Prakash-Ravichandran np
