### ISSUE TITLE
Modification in Help page to prevent horizontal scrolling

### ISSUE THREAD

**Issue by unm07** [Anandsg/Hungry-hero#236]
In the FAQ section of the Help page, when an item is clicked, it gets so large that horizontal scrolling is enabled.
The item can be modified so that it only increases vertically to prevent unnecessary horizontal scrolling.

![Screenshot 2023-10-15 203004](https://github.com/Anandsg/Hungry-hero/assets/110920768/e41cacb5-cbbf-4f9b-a4e5-01002884b9af)

**Comment by unm07** [comment]
May I work on this?

**Comment by Anandsg** [comment]
Go ahead @unm07
