### ISSUE TITLE
[Bug] Clicking on home button or logo is triggering page reload.

### ISSUE THREAD

**Issue by apurvagurme** [Anandsg/Hungry-hero#237]
Clicking on home button or logo is triggering page reload which is not necessary. Instead we can navigate it without reloading.

https://github.com/Anandsg/Hungry-hero/assets/58025903/0753da8c-94f8-422a-997d-6e4c9279e5c5

**Comment by apurvagurme** [comment]
@Anandsg Can you please assign this to me? I will work on it.

**Comment by Anandsg** [comment]
@apurvagurme it is not reloading the page when you click on logo or home it is takes a movement to fetch data from API but it is not reloading the page

**Comment by apurvagurme** [comment]
Oh sorry my bad. I will delete the issue.
