### ISSUE TITLE
Improvement to UI/UX

### ISSUE THREAD

**Issue by adit-shriyans** [Anandsg/Hungry-hero#241]
I wanted to add the following features:
-Use localstorage to store favlist so that favourites are stored even after refreshing
-Fix the starting position of scrollToTop pie chart
-Size of resturant cards should get bigger on hover
-Make it so that the outlined heart icon is visible only upon hovering over resturantCard, but if it is liked, it is always visible

Please assign this issue to me under "hacktoberfest" label

**Comment by isakshamkumar** [comment]
Hey @Anandsg , looks like its been some days and any pr is not being made,So can i work on this issue? Also since i am quite comfortable with the internal logic and working of the cart , is there any that related issue?

**Comment by Anandsg** [comment]
@isakshamkumar I've stopped accepting new changes to the project because some folks aren't following the rules and UI/UX of the application but the app's design has improved a lot. Take a look, and if you find something that needs fixing please make PR i will review the changes
