### ISSUE TITLE
Update README docs

### ISSUE THREAD

**Issue by webdev-vignesh** [Anandsg/Hungry-hero#246]
The current ReadMe file looks sufficient but it can be improved more by

- adding Table Of Contents
- updating Quick Start with more clear instructions
- moving Contributing guide to ReadMe
- giving title "Contributors" for the list of people shown already

**Comment by Anandsg** [comment]
Assigned the issue

**Comment by webdev-vignesh** [comment]
Thank you for the opportunity! 🌟 @Anandsg
