### ISSUE TITLE
[bug report] : show popup when user add item to favourites

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#25]
Currently, our app doesn't provide any confirmation or feedback when users add items to their favourites. We would like to enhance this experience by implementing a feature that displays a confirmation message when an item is successfully added to the user's favourites.

Reference:
checkout closed pull request - Add to favourite functionality (https://github.com/Anandsg/Hungry-hero/pull/23) for the logic.

**Comment by subhashree9898** [comment]
@Anandsg please assign this issue to me!

**Comment by Anandsg** [comment]
@subhashree9898 Sure, could you share if you have experience/developed with similar features? We're also curious about your proposed approach – how would you tackle this challenge?

**Comment by Ravina-Deogadkar** [comment]
Can I work on this?

I am thinking to show a toast message

**Comment by Anandsg** [comment]
@Ravina-Deogadkar yes you can before that could you please fix the footer issue and take this task. i have commented in your PR

**Comment by rashen33** [comment]
Hey, I'd like to work on this.

**Comment by Anandsg** [comment]
@rashen33 Sure brother! please fork the latest version of the repo i just updated the API.

**Comment by ShahIsCoding** [comment]
hi @Anandsg created a pull request[#42 ]

**Comment by Anandsg** [comment]
some other developer worked on this.
