### ISSUE TITLE
[Add]: Adding profile page

### ISSUE THREAD

**Issue by AyusGup** [Anandsg/Hungry-hero#258]
please assign this issue to me under hacktoberfest

**Comment by Anandsg** [comment]
what profile page are you going to add ?

**Comment by AyusGup** [comment]
user profile will be displayed there in which he can update his details and password added using signup

**Comment by AyusGup** [comment]
@Anandsg while working on the issue i am facing issue redirect_uri_mismatch as i am working on localhost and your uri is different i tried with localhost uri but not work.
please suggest what i can do now?
