### ISSUE TITLE
feat - Greet the contributors 

### ISSUE THREAD

**Issue by Junaid-Mohamed** [Anandsg/Hungry-hero#261]
## Feature 

I would like to implement a feature of greeting  the contributors when they open an ***Issue or PR*** using ***Github actions and workflows*** and add  a personalized comment for the contributors 

Sample comment example is as follows :
<img width="676" alt="github-action-bot-comment" src="https://github.com/Anandsg/Hungry-hero/assets/64761352/31e438f2-7e0f-4fef-a0ca-f24af6ff5244">

**Comment by Anandsg** [comment]
Interesting, go ahead

**Comment by Junaid-Mohamed** [comment]
Thanks @Anandsg , do you have anything specific to be added for ***comment*** ? if so please specify it

- [ ] When a contributor opens an issue : 

- [ ] When a contributor opens a PR :  

also, can you add label of ***hackoberfest*** for this feat?
