### ISSUE TITLE
Regarding Login and Cart integration

### ISSUE THREAD

**Issue by isakshamkumar** [Anandsg/Hungry-hero#266]
Currently if a user is not logged in, he can explore different restaurants and their menu and add them to the cart. But When the user clicks on place order button, firstly he should be logged in to do so and  their should be a animation that says something like placing your order and something like email is sent(lile zomato,swiggy)

**Comment by Anandsg** [comment]
ok approach is good.

**Comment by isakshamkumar** [comment]
Yeah working on it Please add hacktoberfest label to it!

**Comment by Junaid-Mohamed** [comment]
Hi @isakshamkumar , can you help me setup this project locally?

**Comment by isakshamkumar** [comment]
Made a pull request, please review

**Comment by isakshamkumar** [comment]
> Hi @isakshamkumar , can you help me setup this project locally?

Sure, what issue are you facing?

**Comment by Junaid-Mohamed** [comment]
> > Hi @isakshamkumar , can you help me setup this project locally?
> 
> Sure, what issue are you facing?

I'm facing this error, what all is tools is required to setup this project locally? @isakshamkumar 
<img width="742" alt="error_stack" src="https://github.com/Anandsg/Hungry-hero/assets/64761352/d91a0ba2-b6ba-42b8-b52d-26946a60ef0c">

**Comment by Anandsg** [comment]
@Junaid-Mohamed No external setup is required to run the app in your local, just fork the repo from master branch just run npm install that will work if you still face the problem revert back. i don't think other are facing this issue for them it is working fine also i have just now tried working as expected for me
