### ISSUE TITLE
[Bug] : No add to cart feature

### ISSUE THREAD

**Issue by Hardik2972** [Anandsg/Hungry-hero#277]
### Screenshots

![Screenshot 2023-10-24 131011](https://github.com/Anandsg/Hungry-hero/assets/115338787/c8e67a7b-af95-445e-a536-02f80b18bbb5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anandsg** [comment]
@Hardik2972 there is a way to add items to cart expand the accordion you'll get
