### ISSUE TITLE
[Refactor request]: Hide clear cart button and cart number on empty cart

### ISSUE THREAD

**Issue by sarojdahal8848** [Anandsg/Hungry-hero#28]
Currently, our app is showing clear cart button and cart count number, even if there is no item in cart. I think I doesn't make any sense of placing clear cart button when cart is empty. 

![image](https://github.com/Anandsg/Hungry-hero/assets/59774795/f4bd13dc-ce2f-4e98-977b-952e67db0221)

**Comment by sarojdahal8848** [comment]
@Anandsg if you think this change is required, you can assign it to me.

**Comment by sarojdahal8848** [comment]
@Anandsg could you please, label it to hacktoberfest?

**Comment by Anandsg** [comment]
@sarojdahal8848 would it be possible to update README file as well

**Comment by sarojdahal8848** [comment]
@Anandsg yes for sure. Could you please reopen pr?

**Comment by Anandsg** [comment]
@sarojdahal8848 could you please check if you are able to update the PR now

**Comment by Anandsg** [comment]
refactor has been implemented by the contributor
