### ISSUE TITLE
Console cleanup

### ISSUE THREAD

**Issue by vignesh-murugan-dev** [Anandsg/Hungry-hero#282]
### Describe the bug

When we check the console of our project we can see that many ppl have made changes without removing the console.log() outputs.

It doesn't affect the app performance or UI, but it's a good practice to prevent these data from being logged into the console.

### Expected behaviour

A much cleaner console without our data being logged uselessly by removing all the console.log() from all the js files.

### Screenshots

![IMG-20231025-WA0001](https://github.com/Anandsg/Hungry-hero/assets/108517094/cfbc456d-796a-4b0c-ab84-4539ba2de606)
![IMG-20231025-WA0002](https://github.com/Anandsg/Hungry-hero/assets/108517094/addfbbc6-5417-423e-b7a5-e283ded72406)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anandsg** [comment]
ok go ahead @webdev-vignesh
