### ISSUE TITLE
[Bug report] : Prevent page reload when navigating from "empty favourites page"

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#286]
### Describe the bug

When a user goes to their favourites and finds no favourite items, they have the option to click on the "Find your favourite restaurants now" arrow, which should take them to the home page. However, the problem is that clicking on this arrow triggers a page reload. This page reload is unnecessary and can be a suboptimal user experience.

### Expected behaviour

When the user clicks on the "Find your favourite restaurants now" arrow from the empty favorites page, the application should navigate to the home page without triggering a full page reload.

### Screenshots

<img width="1334" alt="Screenshot 2023-10-26 at 12 37 29 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/e7f43bef-ae19-4f76-a435-15f04a9ff0b7">

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MurtazaShikari** [comment]
i am working on this issue @Anandsg
