### ISSUE TITLE
Bug: Small grammatical error in About Page

### ISSUE THREAD

**Issue by original-subbaman** [Anandsg/Hungry-hero#288]
### Describe the bug

Grammatical error on this line: "Our team of Frontend Developers is committed to creating a top-notch online ....." 

### Expected behaviour

The line should be changed to: "Our team of Frontend Developers are committed to creating a top-notch online ...." as the noun 'Frontend Developers' is plural. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anandsg** [comment]
assigned the issue
