### ISSUE TITLE
Restaurant Card is Clickable only on Selected areas

### ISSUE THREAD

**Issue by ankit-ask** [Anandsg/Hungry-hero#292]
### Describe the bug

Currently, on the restaurant listing page, the card is clickable only where the content is, and any area wihtout content isn't clickable.

![Screenshot 2023-10-30 at 18 07 02](https://github.com/Anandsg/Hungry-hero/assets/18434128/54d5ad91-6872-4d71-af0f-fc72fc1b5196)

For instance, in the above screenshot, white-space below the 30% off area isn't clickable. The same goes for the whitespace around the image.

### Expected behaviour

The complete restaurant card should be clickable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anandsg** [comment]
@ankit-ask go ahead assigning the issue
