### ISSUE TITLE
Responsiveness and FetchAPI

### ISSUE THREAD

**Issue by vasujhawar2001** [Anandsg/Hungry-hero#3]
1) Not able to view realtime dynamic content on web app. mIght be due to expired api token
2) The application navbar is not responsive for smaller screen sizes.

![Issue 1](https://github.com/Anandsg/Hungry-hero/assets/59659588/07c50a62-abf0-401a-8a35-c1841ad7ea34)
![Screenshot from 2023-09-21 11-12-51](https://github.com/Anandsg/Hungry-hero/assets/59659588/725264e1-ca26-4358-b756-6fe012c4083f)

Hi there @Anandsg if you want me to assign and fix the issue 2, let me know.

**Comment by Anandsg** [comment]
Hello @vasujhawar2001 thank you so much for looking into it.

1. The API working fine in my system please make sure you have installed CORS extension for the chrome, refer the working screenshot
<img width="1432" alt="Screenshot 2023-09-21 at 12 23 17 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/d23037e6-0651-4bc8-8fc8-026279c9b3ab">

2. yes the app is not responsive, please proceed with contributing towards responsiveness i will assign the issue

**Comment by vasujhawar2001** [comment]
Okay, I will start with this.

**Comment by AthN3090** [comment]
> Hello @vasujhawar2001 thank you so much for looking into it.
> 
> 1. The API working fine in my system please make sure you have installed CORS extension for the chrome, refer the working screenshot
> 
> <img alt="Screenshot 2023-09-21 at 12 23 17 PM" width="1432" src="https://user-images.githubusercontent.com/109084312/269517656-d23037e6-0651-4bc8-8fc8-026279c9b3ab.png">
> 2. yes the app is not responsive, please proceed with contributing towards responsiveness i will assign the issue

Shouldn't the fetch API work regardless of whether the user has the extension or not. It is also not working in my system. If it does require the extension, how is it going to work on mobile browsers?

**Comment by Anandsg** [comment]
@AthN3090  The proxy server can make requests to the Swiggy API on behalf of mobile app and then relay the data back to the app. Since the proxy server runs on a server, it can handle CORS issues on behalf of the app. When you make a request from a laptop or mobile device, these CORS restrictions come into play.

Please install cors extension in your laptop and let me know if you need any clarifications

**Comment by vasujhawar2001** [comment]
@Anandsg Definitely need a fix for the CORS error, if you want the app to run in production. Otherwise bad user experience.

**Comment by Anandsg** [comment]
@vasujhawar2001 Sure, since the Swiggy API has CORS restrictions, in order to run this app user must install extension, it can make the user experience frustrating. I'll definitely look for another way to solve this issue

**Comment by AthN3090** [comment]
@Anandsg Hey bro. I have the project running on my system. I understand the responsiveness of the app is still in works. I am still confused about the idea behind the app, can you clarify on the direction for this project. Tell me about extra features you would like to implement, or maybe change the idea itself. :)

**Comment by Anandsg** [comment]
@AthN3090 This application primarily serves as a showcase of our skills and capabilities. While its primary purpose is not for production use, it's essential to address several issues identified in the app related to the search feature, cart functionality, footer placement, and other components. I have created Issue for them please check out and let me know whichever you are comfortable with i will assign the issue to your bucket.
