### ISSUE TITLE
[Bug Report]: Cart remains empty on refreshing page

### ISSUE THREAD

**Issue by sarojdahal8848** [Anandsg/Hungry-hero#33]
If I refresh page after adding items to cart, all data is removed from the state. It makes user experience bad, if I have to add to cart every time I refresh the page.

**Solution:**
We can persist cart state using a library called `redux-persist` on local storage.

**Comment by sarojdahal8848** [comment]
@Anandsg if it requires further discussion let's do it or else you can assign it to me.

**Comment by Anandsg** [comment]
@sarojdahal8848 Yeah! using redux persist for cart state persistence is a good solution, Users will have access to their cart items even if they close and reopen the browser.

**Comment by Anandsg** [comment]
issue has been resolved as part of https://github.com/Anandsg/Hungry-hero/pull/34
