### ISSUE TITLE
[feature request] : Improve Responsiveness of Restaurant Cards and Search Box, and Buttons

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#36]
**Description:**

Our current restaurant cards, search box, and buttons in the body of the application may not display optimally on various screen sizes and devices. We would like to enhance the responsiveness of these elements to provide a seamless user experience across different platforms.

**Issue Details:**

- The restaurant cards should adapt and look good on both desktop and mobile devices.
- The search box, favorite button, and rating button should also be made responsive to ensure easy usage on various screen sizes.
- Ensure that the layout, images, and content adjust appropriately based on screen size.
- Test and address any issues related to alignment, spacing, and readability on smaller screens..

**Additional Information:**

If you have any design suggestions or specific changes in mind to improve the responsiveness of these cards, please feel free to share them.

<img width="872" alt="Screenshot 2023-10-03 at 8 42 47 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/97fada1d-eb97-46c7-8a26-533a2fc82679">

**Comment by mhamzanadeem** [comment]
can u assign me this issue ?  i am participating in hacktoberfest 2023

**Comment by Anandsg** [comment]
@mhamzanadeem Great, Have you had experience working on responsive features in React before? I'm interested in discussing your approach to achieve this.

**Comment by rjangid9080** [comment]
Hey @Anandsg , Can you assign this issue to me.

**Comment by Anandsg** [comment]
@rjangid9080 sure, Have you had any experience / developed such features in react before?

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem Great, Have you had experience working on responsive features in React before? I'm interested in discussing your approach to achieve this.

Hello @Anandsg,

Thank you for considering my input. I have experience in developing React websites, and you can find more details about my work on my LinkedIn profile: (https://chat.openai.com/c/www.linkedin.com/in/hamza-nadeem2000).

Regarding your request for an approach, I would suggest making tailored adjustments in the Tailwind CSS of your codebase. If you're interested in a more detailed explanation of my approach, I'd be happy to provide it.

Looking forward to potentially collaborating on this project.

**Comment by Anandsg** [comment]
> > @mhamzanadeem Great, Have you had experience working on responsive features in React before? I'm interested in discussing your approach to achieve this.
> 
> Hello @Anandsg,
> 
> Thank you for considering my input. I have experience in developing React websites, and you can find more details about my work on my LinkedIn profile: (https://chat.openai.com/c/www.linkedin.com/in/hamza-nadeem2000).
> 
> Regarding your request for an approach, I would suggest making tailored adjustments in the Tailwind CSS of your codebase. If you're interested in a more detailed explanation of my approach, I'd be happy to provide it.
> 
> Looking forward to potentially collaborating on this project.

Okay, assigning the issue to you. Make sure install CORS extension for the chrome to run this app in your local machine. Thank you.

**Comment by rjangid9080** [comment]
Hi @Anandsg ,

Thank you for considering.  Let me introduce myself, I am frontend engineer and having experience to develop websites with React JS, Tailwind CSS , Next JS.  You can check my LinkedIn  profile for more - https://www.linkedin.com/in/rohit-jangid-250893189 .

Looking forward to potentially collaborating on this project.

**Comment by Anandsg** [comment]
@rjangid9080 Thanks brother, since other developer already assigned to this feature, could you please pick other issues or you can raise issue if you found anything to improve the user experience of the app.

**Comment by mhamzanadeem** [comment]
@Anandsg  can u guide me which CORS chrome extension do You use for your app?
![heifheifh](https://github.com/Anandsg/Hungry-hero/assets/114602354/023b1d99-bcb2-447e-bbf4-76705be180c8)

**Comment by Anandsg** [comment]
the 3rd one control allow origin

https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

**Comment by mhamzanadeem** [comment]
@Anandsg  I have installed CORS app ,  and toggle it on and  i have test the CORS options but still your app is not running on my local machine . Can u help me out 
![7878787](https://github.com/Anandsg/Hungry-hero/assets/114602354/d2e8ea77-804e-4fd6-bd87-42b949240f3e)

**Comment by Anandsg** [comment]
> @Anandsg I have installed CORS app , and toggle it on and i have test the CORS options but still your app is not running on my local machine . Can u help me out ![7878787](https://user-images.githubusercontent.com/114602354/272244569-d2e8ea77-804e-4fd6-bd87-42b949240f3e.png)

oh, not sure other developer are able to run this app. can you fork the latest version of the app and try ? i see unexpected token error in the app.js file have u tried to modify anything, please check and circle back

**Comment by ronisarkarexe** [comment]
@Anandsg Can I create an issue for an alternative way to open the application without installing CORS?

**Comment by mhamzanadeem** [comment]
@Anandsg can u help me what mistake i am doing ? 
![111](https://github.com/Anandsg/Hungry-hero/assets/114602354/59b7971f-71c0-4cba-8520-6d0f84a245d3)

These are the options of CORS
![222](https://github.com/Anandsg/Hungry-hero/assets/114602354/13f45ace-2ab5-4888-b095-afd7fb24ef77)

**Comment by Anandsg** [comment]
hey bro have you forked updated repo ?

**Comment by Anandsg** [comment]
can you join here if you don't mine difficult to guide through this channel 

Google meet link :

https://meet.google.com/eua-ivnf-haw

**Comment by mhamzanadeem** [comment]
@Anandsg why had you unassigned me

**Comment by Anandsg** [comment]
sorry it was by mistaken you can continue i will reassign

**Comment by mhamzanadeem** [comment]
@Anandsg  Can u tell me , Now it looks better  or not ? 

![999](https://github.com/Anandsg/Hungry-hero/assets/114602354/3fabc5ac-4e74-4af7-814b-27a3dbe39da7)

**Comment by Anandsg** [comment]
> @Anandsg Can u tell me , Now it looks better or not ? i know it needs improvement
> 
> ![999](https://user-images.githubusercontent.com/114602354/272621112-3fabc5ac-4e74-4af7-814b-27a3dbe39da7.png)

it cools ok can we include only one restaurant card when it's small devices also search box and other button needs to be aligned, please refer the screenshot attached for you reference

<img width="508" alt="Screenshot 2023-10-04 at 8 39 16 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/d2cedb37-026c-4794-bad5-f06afc48b49f">

**Comment by Mafildo** [comment]
If possible I want to contribute too!

**Comment by mhamzanadeem** [comment]
@Anandsg  Does it looks better or not ?  
any suggestions ? 
![99999](https://github.com/Anandsg/Hungry-hero/assets/114602354/0742b74e-5700-45f3-b39a-cba23d6b736e)

**Comment by Anandsg** [comment]
@mhamzanadeem yeah looks good bro, can we make restaurant card little small, also focus on buttons please!!

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem yeah looks good bro, can we make restaurant card little small, also focus on buttons please!!

ok , i will work on it

**Comment by Anandsg** [comment]
@rjangid9080  Results looks amazing brother, and no comments about result in small devices please have a look at my response

1. Considering the aesthetics, would it be advisable to change the color of the rating and favorite buttons to an orange ? This adjustment would harmonize the buttons with the search button, creating a unified visual theme.

- response: I've actually already attempted to change the colour of the ratings to orange, but trust me, it didn't look great. I have a different idea in mind: we could implement a feature where ratings < 4 appear in gray, while ratings 4 and above are displayed in green. This green colour makes more sense to when we have this feature (I'll open an issue for it, but it's not needed now).
- As for the search button, we could consider making some adjustments to its border, but having it entirely orange seems a bit too overwhelming. Feel free to change the color if you believe it would look better, or we can revisit it later

3. Could you kindly advise on increasing the size of the rating box (the element highlighted in green on each restaurant card)? This enhancement aims to draw more attention to this crucial piece of information.
- response: yes do it. 

4. Additionally, I am contemplating adjusting the text size of the "span" elements within each restaurant card. This modification is intended to improve readability and ensure that all information is presented clearly.
- response: yes do it. 

I've got a minor suggestion regarding the search box, rating button, and favourites on BIG screens. Instead of shifting them all the way to the left, how about positioning them slightly to the left and above the restaurant cards? I believe it would enhance the overall look. I've even marked the proposed placement in the image below for reference.
<img width="1378" alt="Screenshot 2023-10-04 at 11 18 00 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/40dfecc6-8f8f-4ada-9769-d02cd7f222c4">

**Comment by mhamzanadeem** [comment]
ok , i will do

**Comment by mhamzanadeem** [comment]
@Anandsg  work has completed !  Take a moment to review the recent modifications I have made to the project. If my work need improvement ; give me suggestions

![11](https://github.com/Anandsg/Hungry-hero/assets/114602354/9091180d-f1f9-490f-a50b-67f258415f2e)

![22](https://github.com/Anandsg/Hungry-hero/assets/114602354/358681a1-01a5-4dcd-b4d9-7692384dc413)

**Comment by Anandsg** [comment]
This looks good @mhamzanadeem , can i get screenshot of menu list in mobile view?

**Comment by mhamzanadeem** [comment]
> This looks good @mhamzanadeem , can i get screenshot of menu list in mobile view?

@Anandsg  
![1111](https://github.com/Anandsg/Hungry-hero/assets/114602354/17e6d1c6-98ee-4ed4-a1ec-dd9e47dcaf3c)

**Comment by Anandsg** [comment]
@mhamzanadeem this looks good, what about Menu list items? is that coded for responsive ?
<img width="549" alt="Screenshot 2023-10-05 at 9 50 29 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/41ca978b-1153-443c-adf9-1df050aacf8c">

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem this looks good, what about Menu list items? is that coded for responsive ? <img alt="Screenshot 2023-10-05 at 9 50 29 AM" width="549" src="https://user-images.githubusercontent.com/109084312/272779465-41ca978b-1153-443c-adf9-1df050aacf8c.png">
 
@Anandsg  i didnt understand ! .  how do you open this menu List  ?

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem this looks good, what about Menu list items? is that coded for responsive ? <img alt="Screenshot 2023-10-05 at 9 50 29 AM" width="549" src="https://user-images.githubusercontent.com/109084312/272779465-41ca978b-1153-443c-adf9-1df050aacf8c.png">

@Anandsg  can you provide some suggestions for responsiveness of menu List

**Comment by Anandsg** [comment]
@mhamzanadeem I recommend adding responsiveness to the menu list items. Since you've already made much contributions to the app, I'd like to give other developers a chance. If no one is available, I'll create an issue for the menu list responsiveness and assign it to you, considering your familiarity with the code. To prevent conflicts, it's best to make a pull request for now. I'll review it, and if any further changes are needed, I'll let you know.

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem I recommend adding responsiveness to the menu list items. Since you've already made much contributions to the app, I'd like to give other developers a chance. If no one is available, I'll create an issue for the menu list responsiveness and assign it to you, considering your familiarity with the code. To prevent conflicts, it's best to make a pull request for now. I'll review it, and if any further changes are needed, I'll let you know.

ok 
I will make Pull request .
You can raise another issue of menu List . I will do contribution  in that issue

**Comment by Anandsg** [comment]
@mhamzanadeem before contributing to Menu list i have few suggestion regarding your PR let me review it once

**Comment by mhamzanadeem** [comment]
> @mhamzanadeem before contributing to Menu list i have few suggestion regarding your PR let me review it once

ok . review it first
