### ISSUE TITLE
[feature request]: Create scroll to top button

### ISSUE THREAD

**Issue by ronisarkarexe** [Anandsg/Hungry-hero#38]
Description:

new feature:

- When the user reaches the buttom section, they can easily move the button to the top with a single click.

![addFreature](https://github.com/Anandsg/Hungry-hero/assets/76697055/64aa97e2-66c8-45f8-9522-35817ba7d067)

**Comment by rjangid9080** [comment]
Hey @Anandsg , Please Assign to me

**Comment by Anandsg** [comment]
@rjangid9080 please work on it, @ronisarkarexe thanks for the help towards improving the user experience of our app.

**Comment by rjangid9080** [comment]
@Anandsg Could you please add label of hacktoberfest ?

**Comment by Anandsg** [comment]
> @Anandsg Could you please add label of hacktoberfest ?

Added

**Comment by Anandsg** [comment]
feature has been developed
