### ISSUE TITLE
Favicon Update Required

### ISSUE THREAD

**Issue by tmsagarofficial** [Anandsg/Hungry-hero#39]
I would like to point out that a proper favicon would really help in improving the user experience by making this site uniquely identifiable from a group of tabs.
<img width="115" alt="image" src="https://github.com/Anandsg/Hungry-hero/assets/110724849/434e3412-0c70-4e69-99d2-4be3785a01a8">

Pls, assign this issue to me so that I can start working on the same. @Anandsg

**Comment by Anandsg** [comment]
yes please i was about to create an issue for this please proceed, you can use our app's logo for the favicon

**Comment by tmsagarofficial** [comment]
Thanks for assigning. Will start working on this 🚀

**Comment by Anandsg** [comment]
@tmsagarofficial you can find it in utils/constants/LOGO_URL

**Comment by tmsagarofficial** [comment]
Can I like upload the favicon here in the repo and then give link to that??

If yes tell me which folder/directory to upload

**Comment by tmsagarofficial** [comment]
Like see to use that as a favicon I would be converting it to a .ico file right.. so where do u want me to upload that in this repo and then can I give path to that as link in that constants???

**Comment by Anandsg** [comment]
ok ok, you can keep that icon in assets brother then use in your code

**Comment by Anandsg** [comment]
This got resolved as per the requirement

**Comment by tmsagarofficial** [comment]
OKay not a problem 🚀

**Comment by Anandsg** [comment]
@tmsagarofficial please pick any issue / feature if you want to contribute thanks for cooperating
