### ISSUE TITLE
Search feature is not working

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#4]
**Issue Description:**
When users search for restaurants using the search box in the Body.js component, they are encountering an issue where the system incorrectly displays the message, "The restaurant you're searching for doesn't exist," even when the restaurant they are looking for is present in the App. This issue needs to be addressed to improve the search functionality.

**Expected Behaviour:**
Users should receive accurate search results that match the restaurants available in the app when they input a restaurant name into the search box. The system should not display false negatives, such as "The restaurant you're searching for doesn't exist."

<img width="1432" alt="Screenshot 2023-09-24 at 8 31 48 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/66d60c13-9d9a-472e-a384-c4a1f9d21258">

**Comment by ronisarkarexe** [comment]
@Anandsg Could you please assign me this task?

**Comment by Anandsg** [comment]
@ronisarkarexe assigning this to your bucket
