### ISSUE TITLE
[Bug Report] : Recommended items not getting displayed for Bakingo

### ISSUE THREAD

**Issue by rjangid9080** [Anandsg/Hungry-hero#40]
Items are not getting displayed for the Bakingo Restaurant .

For Your Reference
![image](https://github.com/Anandsg/Hungry-hero/assets/43642227/91ee13dc-76ef-42fe-a5fb-b1c0365917b6)

**Comment by Anandsg** [comment]
@rjangid9080 yes for some restaurants there might be no details present, would you like to dive into it i will assign this issue?

**Comment by rjangid9080** [comment]
@Anandsg ok please assign

**Comment by utkarshtenguriya** [comment]
Hey Can you  assign this to me @rjangid9080 I will like to contribute to it

**Comment by Anandsg** [comment]
This is working fine now
