### ISSUE TITLE
[bug report] :Need feedback After Clearing item form favourite

### ISSUE THREAD

**Issue by ronisarkarexe** [Anandsg/Hungry-hero#41]
Issue Description:
When a user removes their favorite item, the application currently does not provide any indication that there are no favorite items available.

Expected Behaviour:
- After clearing an item, you will receive a message indicating that the item is now available.
- You will be redirected to the home page or add a navigation button or link,  so that you can continue exploring the application.

![fevlist](https://github.com/Anandsg/Hungry-hero/assets/76697055/1a82e035-62be-4984-9685-2b412a52c578)

**Comment by Anandsg** [comment]
@ronisarkarexe absolutely, would you like to work on it?

**Comment by ronisarkarexe** [comment]
> @ronisarkarexe absolutely, would you like to work on it?

assign me
