### ISSUE TITLE
Enhance empty cart message with Icon/Image

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#43]
when the cart is empty, our app displays a message that says, "Your cart is empty." While this message is informative, we believe that adding a visual element in the form of an icon or image can greatly enhance the user experience.

We've got the design structure we're itching to incorporate into our app, it's below!"

<img width="1258" alt="Screenshot 2023-10-03 at 10 22 33 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/69a130b5-a22f-4a6a-8c1e-2f1601b85f31">

**Comment by DarkSoul26** [comment]
Hey @Anandsg, please assign this to me, I'll take a look into it

**Comment by Anandsg** [comment]
@DarkSoul26 done please install the extension to run the app in your system (have a look at README.md file)

**Comment by DarkSoul26** [comment]
@Anandsg check this, #46

**Comment by Anandsg** [comment]
Feature has been implemented and merged
