### ISSUE TITLE
[bug report] : Missing Footer on Home Page and the Footer Needs a Fix

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#45]
**Issue Description:**
We've got a two-in-one issue here. firstly the footer is missing on home page, secondly, when there are few or no restaurants found in the app, the footer misbehaves and ends up in the middle of the page. This disrupts the user experience and the layout of the app. 

**Expected Behaviour:**
The footer should stay put at the bottom of the page, no matter how many or few restaurants are displayed. It should not wander off to the middle of the page when search results are limited. We need to fix this to ensure a smoother user experience.
<img width="1423" alt="Screenshot 2023-09-24 at 8 34 36 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/a7be4ff9-82df-4794-a365-848adfd6f51d">

**Comment by Jai-Marothiya** [comment]
Hi @Anandsg, 
I reviewed your code and I think I can fix the footer section of your code I also understand the bug that presents.
It's a pleasure for me to fix it, kindly assign this task to me.

Regards
Jai Marothiya

**Comment by Anandsg** [comment]
@Jai-Marothiya done.

**Comment by Anandsg** [comment]
This feature has been implemented closing the issue.

**Comment by Jai-Marothiya** [comment]
Please Add the label of Hacktoberfest accepted.

**Comment by Jai-Marothiya** [comment]
Hi @Anandsg, 
Please add this merge request with the Hacktoberfest tag merge because this contribution is still not shown on my Hacktoberfest profile page.

Thanks
