### ISSUE TITLE
Making a modern ui for /contact

### ISSUE THREAD

**Issue by Vatsalmadhur** [Anandsg/Hungry-hero#49]
I want to develop a clean and modern UI for the contact page. The form will have a background as we have it on the about page,and the submit button will be highlighted.
![Screenshot 2023-10-04 at 11 22 10 AM](https://github.com/Anandsg/Hungry-hero/assets/107473447/b1c8eb79-5b08-4551-b9a4-07e0fc3bb5d7)

**Comment by Vatsalmadhur** [comment]
I request you to assign me this issue

**Comment by Anandsg** [comment]
that's great i was about to create an issue for this please go ahead.

**Comment by Prakharpandey007** [comment]
Please assign this issue to me. I'll make sure that all these points are considered well.
Looking forward for a positive response.
Thank You!

**Comment by Anandsg** [comment]
@Prakharpandey007 the other developer already assigned, can you check the app and raise issue/feature request that helps our app to improve user experience.

**Comment by Anandsg** [comment]
@Vatsalmadhur the contact page has been updated with basic validations please fork the latest version of the repo and add your changes, thanks

**Comment by Vatsalmadhur** [comment]
Ok sure no issues

**Comment by Anandsg** [comment]
ok @Vatsalmadhur

**Comment by Vatsalmadhur** [comment]
Apologies for the delay, I have made a pull request.  @Anandsg ,please review pr #112 .
