### ISSUE TITLE
Fix footer at bottom

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#5]
**Issue Description:**
When there are minimal or no restaurants found in the app, the footer is mispositioned and appears in the middle of the page. This issue affects the overall user experience and layout of the application. check out Footer.js component for the code

**Expected Behaviuor:**
The footer should maintain its proper position at the bottom of the page, regardless of the number of restaurants found in the app. It should not move to the middle of the page when there are few or no search results.
<img width="1423" alt="Screenshot 2023-09-24 at 8 34 36 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/a7be4ff9-82df-4794-a365-848adfd6f51d">

**Comment by Anandsg** [comment]
@Ravina-Deogadkar yeah sure, go for it 
assigning it to you 🚀

**Comment by Rohit-Sharmaa** [comment]
hey @Anandsg  can i work on this issue

**Comment by Anandsg** [comment]
Hey there, @Rohit-Sharmaa! It's fantastic to see your enthusiasm. However, it seems that user @Ravina-Deogadkar has already forked the repo and started tackling on this issue. could you please check out the issue #4  and leave a comment? That way, I can assign it to you if you're up for the challenge. else you can explore the app and raise a new issue. Thanks!

**Comment by Rohit-Sharmaa** [comment]
@Anandsg No problem

**Comment by Anandsg** [comment]
@Rohit-Sharmaa Would you like to work on this issue?
