### ISSUE TITLE
fix : help section / page allignment issue

### ISSUE THREAD

**Issue by rohitroy-github** [Anandsg/Hungry-hero#50]
The help section/page alignment seems a bit messy. I can fix this if you want, contributing in accordance with Hacktoberfest ! 

![image](https://github.com/Anandsg/Hungry-hero/assets/68563695/cb187618-7085-4765-ab68-1ecc53ef0f6d)

**Comment by Anandsg** [comment]
@rohitroy-github sure thanks for noticing, i will add the hacktoberfest labels please work on it

**Comment by Anandsg** [comment]
@rohitroy-github the footer has fixed you can focus on accordions fork the latest version if possible.

**Comment by rohitroy-github** [comment]
Cool.
