### ISSUE TITLE
fix / improve : spacing

### ISSUE THREAD

**Issue by rohitroy-github** [Anandsg/Hungry-hero#51]
The page contents looks a bit spread to the sides if I compare them with any food delivery app like Swiggy ! 

For example, this is Swiggy >>>

![image](https://github.com/Anandsg/Hungry-hero/assets/68563695/35ff3972-041e-4b3c-ab88-0447efc766bf)

But this is yours >>> 

![image](https://github.com/Anandsg/Hungry-hero/assets/68563695/44f45bf4-9497-4d57-a31b-13dd4bec651c)

So I would like to make this a bit compact it it's okay with you ?

**Comment by Anandsg** [comment]
@rohitroy-github okay, assigning the issue
