### ISSUE TITLE
Navbar fonts did't matched

### ISSUE THREAD

**Issue by rohitdubey1352** [Anandsg/Hungry-hero#55]
Navbar fonts did't matched with the overall fonts and its making bad impression.
Assign me this task to fix this @Anandsg

**Comment by Anandsg** [comment]
@rohitdubey1352 Do you have any example or reference websites in mind? It would be helpful for me to see them to better understand the style you want for our app. you can proceed once i give go ahead

**Comment by rohitdubey1352** [comment]
If you can see in the navbar, the fonts are same, and they have good sense of fonts and if you compare with others font on this website they have others font and the continuing using the same font.
So, my conclusion is I want to add some smooth and best font for your **Navbar**

![image](https://github.com/Anandsg/Hungry-hero/assets/56528673/844ce5ee-7b65-4178-b0e0-dc9625aa7344)

**Comment by Anandsg** [comment]
Okay @rohitdubey1352

**Comment by Anandsg** [comment]
done please work on it @rohitdubey1352

**Comment by rohitdubey1352** [comment]
Sure, I will do that
