### ISSUE TITLE
Basic form validations required

### ISSUE THREAD

**Issue by Pooja-Lohar25** [Anandsg/Hungry-hero#56]
Contact form validations and error messages are required in case of wrong user inputs.

![formvld](https://github.com/Anandsg/Hungry-hero/assets/73185303/55714ff1-0ac6-4f4b-8b83-184ed7c9d043)

@Anandsg  kindly assign me this under hacktoberfest

**Comment by Anandsg** [comment]
@Pooja-Lohar25 Cool go for it.

**Comment by Pooja-Lohar25** [comment]
Kindly label the issue under hacktoberfest

**Comment by Anandsg** [comment]
> Kindly label the issue under hacktoberfest

done @Pooja-Lohar25
