### ISSUE TITLE
[Enhancement] : Change heart icon color on hover in RestaurantCard component

### ISSUE THREAD

**Issue by fiskryeziu** [Anandsg/Hungry-hero#58]
### Desc
Add a hover effect to change the heart icon color in the RestaurantCard component.

**Comment by fiskryeziu** [comment]
could you please consider adding the "hacktoberfest" label

**Comment by Anandsg** [comment]
> could you please consider adding the "hacktoberfest" label

done

**Comment by Anandsg** [comment]
This has been implemented
