### ISSUE TITLE
Lack of Feedback and Navigation After Clearing Cart

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#6]
**Issue Description:**
When a user clears their cart, the application currently lacks feedback to inform the user that their cart is now empty. Additionally, there is no easy way for the user to navigate back to the home page after clearing the cart.

**Expected Behaviour:**
After the user clears their cart, they should receive a clear and informative message indicating that their "cart is empty". Additionally, a navigation button or link to the home page should be provided to allow the user to continue exploring the app.
<img width="1435" alt="Screenshot 2023-09-24 at 8 37 38 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/3d5b1279-74b0-4ea6-9113-67ede8e5ca27">

**Comment by ronisarkarexe** [comment]
@Anandsg Could you please assign me this task also?

**Comment by Anandsg** [comment]
done @ronisarkarexe
