### ISSUE TITLE
Display a loading spinner when clearing all favourites while redirecting to Home Page

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#60]
Currently, when users remove all items from their favourites, they are instantly redirected to the home page. While this works fine, we want to make it a bit more stylish. How about adding a loading spinner during this transition? I have a design concept in mind, but you're welcome to suggest your own if you prefer.

<img width="1304" alt="Screenshot 2023-10-04 at 11 02 49 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/f0f969c0-c5ee-49f5-ad8d-07998406fa77">

**Comment by Anniebhalla10** [comment]
Idea: Could you assign this to me?

**Comment by Anandsg** [comment]
@Anniebhalla10  Sounds interesting! I'm open to reviewing your solution. I may have some suggestions once I see it in action, so please go ahead with your idea (moving the logo), and we can discuss further."

**Comment by Anniebhalla10** [comment]
@Anandsg I was just going through the platform.
<img width="102" alt="image" src="https://github.com/Anandsg/Hungry-hero/assets/55139659/18794ed2-1ad3-4feb-88c7-1ac909c5340e">
Shouldn't the button label be "Favourites"

**Comment by Anandsg** [comment]
@Anniebhalla10 Absolutely, it's 'favourites' and regarding your UX suggestion I completely agree. Instead of displaying an empty page when users navigate to the 'Favourites' tab with no saved items, it's better to provide them with the freedom to return to the home screen if they wish. and for other 2 bugs i will reach you through linkedIn. Thanks!!

**Comment by Anniebhalla10** [comment]
Okay, Great.

**Comment by Anandsg** [comment]
Issue has been resolved as part of PR https://github.com/Anandsg/Hungry-hero/pull/70
