### ISSUE TITLE
Adding Footer

### ISSUE THREAD

**Issue by vishalverma9572** [Anandsg/Hungry-hero#64]
I want to add a footer to this webpage,please assign this to me

**Comment by Anandsg** [comment]
@vishalverma9572 footer is already there

**Comment by vishalverma9572** [comment]
Yes, But this has only developer details, I am going to improve this..

**Comment by Sanketmane2323** [comment]
I would like to add a good footer for this webiste

**Comment by Anandsg** [comment]
> Yes, But this has only developer details, I am going to improve this..

@vishalverma9572 yeah ok i 

> Yes, But this has only developer details, I am going to improve this..

okay, I'm open to reviewing your solution. please go ahead with your idea and let me suggest once you came up with solution if that well suits our app we can implement it

**Comment by Anandsg** [comment]
@Sanketmane2323 other developer already assigned feel free to pick other issues / u can raise issue request if u found such
