### ISSUE TITLE
There's no way to go back upon searching something

### ISSUE THREAD

**Issue by Shivansh175** [Anandsg/Hungry-hero#68]
I think this is a bug in your project that once you search something there's no any means by which you can go back to your home page directly....and this is extremely terrible.
Look at this ss and none of the links can take me home at this moment...

![Screenshot 2023-10-05 135839](https://github.com/Anandsg/Hungry-hero/assets/112273961/fbadb0b7-fcb5-4d4c-97fb-6c95ac708fc7)
This needs to be fixed, Assign me this issue.

**Comment by Shivansh175** [comment]
please add hacktoberfest and hactoberfest accepted labels to the issue

**Comment by Shivansh175** [comment]
hey @Anandsg i'm having trouble running the project locally over my system please help me out..

**Comment by Anandsg** [comment]
@Shivansh175 what’s the issue?

**Comment by Anandsg** [comment]
@Shivansh175  please run npm install and try or fork the new version of the repo and run npm install, this might work as this repo is working for others, let me know if you still facing the issue

**Comment by Shivansh175** [comment]
i tried both the things but they didn't work 
where is the main html file that has to be run on browser...it must be 'index.html'...?

**Comment by Shivansh175** [comment]
yeah ik that's there but that seems to have no code to be executed....a blank webpage opens up when i run this file

![Screenshot 2023-10-05 221259](https://github.com/Anandsg/Hungry-hero/assets/112273961/f1638f71-18a9-4ee1-8cf1-39034cc26661)

am i referring to some wrong file??

**Comment by ChammounC** [comment]
Hey @Anandsg, please assign this to me.

**Comment by Anandsg** [comment]
Sure @ChammounC you can work on that

**Comment by ChammounC** [comment]
@Anandsg will this do?

![Screenshot 2023-10-09 000128](https://github.com/Anandsg/Hungry-hero/assets/43007452/67042f5f-d7ff-4992-a853-deb3a0bbf190)

![Screenshot 2023-10-09 000206](https://github.com/Anandsg/Hungry-hero/assets/43007452/59572b7f-d782-4a79-baef-b26308c492ae)
