### ISSUE TITLE
[Bug report] : Conflicting behaviour with favourites handling

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#69]
Issue Description 

**Current Behaviour:**
- When a user adds items to their favourites list on the main page, these items appear correctly with a coloured heart icon.
- However, when the user tries to view these favourited items from the favourites page, they can see the items as expected.
- The problem arises when the user returns to the main page and attempts to add more items to their favourites. Instead of adding them to the favourites list, these new items get added to the favourites but disappear from the main page.
- Furthermore, if the user goes back to the favourites page and clicks the favourites button twice, all previously marked favourites and unfavourites are displayed in the favourites section.

**Expected Behaviour:**

- The expected behaviour is that favourited items should remain in the favourites list consistently.
- Additionally, clicking the favourites button twice should not result in displaying both favourites and unfavourites in the favourites section.

**Steps to Reproduce:**

1. Go to the main page.
2. Add some items to the favourites.
3. Navigate to the favourites page and check if the favourited items are there.
4. Return to the main page and try to add more items to the favourites.
5. Observe if the newly added items disappear from the main page.
6. Visit the favourites page again and click the favourites button twice to see if it displays both favourites and unfavourites.

**Screenshots or Additional Information:**

Unfortunately, I couldn't provide screen recordings due to their size, but these steps should help reproduce the issue.

**Assignees:**

Assigning @Anniebhalla10  for this one because she's the one who spotted this bug and suggested that I create an issue for it.

**Comment by Anniebhalla10** [comment]
Could you please assign this to me. Thanks @Anandsg

**Comment by Anandsg** [comment]
This bug has been fixed, closing the issue
