### ISSUE TITLE
Search Box and Top Rating Btn Alignment

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#7]
Currently, our search box and top-rated button are wandering off to the far right when they should be center stage in the body.

Let's give them the spotlight they deserve and move them right to the center!

Looking forward to seeing this issue resolved in style! 💪😎

<img width="1433" alt="Screenshot 2023-09-25 at 1 43 06 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/0a266957-d25a-498c-a47c-f6a4e21f3c74">

**Comment by Mohan1404** [comment]
Hello @Anandsg,
please assign this issue to me under Hacktoberfest, as I  worked on the navbar of some projects, I can make the whole responsive navbar with the required format.

**Comment by Anandsg** [comment]
@Mohan1404 yes go ahead assigning the issue to your bucket.

**Comment by Mohan1404** [comment]
I can't make this issue as the tech stack differs and also getting some issues with Nodejs version.
You can unassign this issue.

**Comment by Anandsg** [comment]
done @Mohan1404  thanks for letting us know.

**Comment by rashen33** [comment]
Hey @Anandsg. I'm looking forward to fix this issue. If this issue is still available assign me.

**Comment by Anandsg** [comment]
Hi @rashen33 the issue is still needs to be resolved you can work on it, assigning issue to you

**Comment by AdarshGachha** [comment]
Hey @Anandsg , I am looking forward to fix this issue. If this issue is still available assign me under hacktoberfest 2023 category.

**Comment by Anandsg** [comment]
@AdarshGachha you can work on it

**Comment by mohitsaini07** [comment]
Hi Anand, I would like to work on this issue if available.

**Comment by Anandsg** [comment]
@mohitsaini07 yes please proceed. make sure to install CORS extension to run this app in the local machine

**Comment by rashen33** [comment]
> Hi @rashen33 the issue is still needs to be resolved you can work on it, assigning issue to you

Please review pr.
