### ISSUE TITLE
[Bug report] : Consistent Offline Handling Across All Pages

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#72]
**Current Behaviour:**

Currently, we have implemented offline handling using window.addEventListener, which displays an error message stating "it appears that the user is currently offline." However, this implementation is limited to the home page. Users can navigate to the Help page, About page, and others even when they are offline. This inconsistency in handling offline situations results in a bad user experience.

**Proposed Approach:**

To improve the user experience, we should make the offline handling message consistent across all pages of the app. Regardless of the page the user is on when they lose internet connectivity, they should receive the message notifying them about their offline status.

**Additional Information:**

Consider the design and styling of the error message to ensure it fits seamlessly with the look and feel of each page.

<img width="1406" alt="Screenshot 2023-10-05 at 7 10 55 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/6a9e95e1-baf4-4796-9d88-c5411dc06577">

<img width="1428" alt="Screenshot 2023-10-05 at 7 11 15 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/afde797a-d9bc-481d-acde-a88a5bd037bb">

**Comment by theDevSoham** [comment]
Hello @Anandsg I can give a try to this. Have some ideas regarding this type of issue. Can you please assign me the task?

**Comment by Anandsg** [comment]
@theDevSoham Hey sure, looking forward for the good solution.
