### ISSUE TITLE
Improving UI of Navbar

### ISSUE THREAD

**Issue by DivyanshiNarang** [Anandsg/Hungry-hero#73]
I can improve the UI of Navbar by providing margin and changing the font style so as to make it more appealing to the users.

![image](https://github.com/Anandsg/Hungry-hero/assets/74779601/5f655790-3ec4-4cb9-a80f-0ef0b1d3ba11)

**Comment by Anandsg** [comment]
okay will review once you create a PR @DivyanshiNarang

**Comment by Aabiskar-dhenga** [comment]
Hey Anandsg can you assign this issue to me >?

**Comment by amrahs02** [comment]
hey @Anandsg  I'd be happy to take ownership of this issue. Please assign it to me.

**Comment by Anandsg** [comment]
@DivyanshiNarang Are you working that or you want me to assign it other developers?

**Comment by DivyanshiNarang** [comment]
@Anandsg I am working on this issue.
