### ISSUE TITLE
Animated FAQs

### ISSUE THREAD

**Issue by arnabpal2022** [Anandsg/Hungry-hero#76]
Can I Work on making the FAQ Sections Animated while clicking? It Looks Static and outdated.

**Comment by Anandsg** [comment]
yup @arnabpal2022

**Comment by isakshamkumar** [comment]
Please assign me this issue, I wanna work on it!

**Comment by arnabpal2022** [comment]
i'm working on it @isakshamkumar

**Comment by Anandsg** [comment]
This has been deployed
