### ISSUE TITLE
[Feature Request] : Add multiple rating filter options to restaurant displaying page

### ISSUE THREAD

**Issue by Brij247** [Anandsg/Hungry-hero#78]
### Description:
Currently, the restaurant displaying page only allows users to filter by a fixed 4+ rating. This can be limiting, as users may want to see restaurants with lower ratings, or restaurants that have a high rating for a specific aspect, such as food quality or service.
![image](https://github.com/Anandsg/Hungry-hero/assets/72482132/efb831dc-48ce-4a04-b36a-0e3aa27ead22)

### Proposed Solution:
A multiple select rating filter would allow users to filter by any combination of ratings, such as 4+ stars for food quality and 3+ stars for service. This would give users more flexibility and allow them to find restaurants that meet their specific needs.
![image](https://github.com/Anandsg/Hungry-hero/assets/72482132/05e68c52-e1d1-4461-9140-6122ff60fcff)

### Additional Information:
The BE endpoint will be filtered based on the options the user select.
**Suggested Options for Select :**

- 4.0+
- 3.0+
- 2.0+

### Benefits:

- More control for users
- More accurate results
- Increased engagement

**Comment by Anandsg** [comment]
@Brij247 This makes sense. I particularly liked your design approach for combining 3+ and 2+ ratings within the same dropdown button; it's incredibly user-friendly. Feel free to proceed with the changes if you'd like.

**Comment by Brij247** [comment]
Thank you for your valuable feedback. I plan to proceed with the changes. Hope you will assign this issue to me soon!

**Comment by Anandsg** [comment]
@Brij247 done

**Comment by prakhar1535** [comment]
i was working on this issue

**Comment by Anandsg** [comment]
> i was working on this issue

This issue says multiple ratings i will create a new issue with exact issue and assign it to ur bucket.

**Comment by prakhar1535** [comment]
works

**Comment by Anandsg** [comment]
else you can directly make PR with suggested changes needs to be done, will merge that if it looks good
