### ISSUE TITLE
[Bug report] : Add - Item added to cart confirmation

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#79]
**Current Behavior:**

Currently, when users add items to their cart, there is no confirmation message or feedback to indicate that the item has been successfully added. This lack of feedback can potentially lead to user confusion and a less-than-ideal shopping experience.

**Proposed Enhancement:**

I propose that we implement a confirmation message when users add items to their cart. This message should provide clear feedback, such as "Item added to cart" or something similar, to reassure users that their action was successful.

**Additional Information:**

I have attached a screenshot that showcases the exact design and position of the confirmation popup message. It should appear in the middle of the page, on top of the content.

<img width="1047" alt="Screenshot 2023-10-06 at 10 25 00 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/bea5b4ad-14d0-44f2-8096-5956be9f44b2">

**Comment by ChammounC** [comment]
Hey @Anandsg , I would like to work on this issue.

**Comment by Anandsg** [comment]
@ChammounC Sure, have you worked on such features in react before ? and i would love hear your approach towards this

**Comment by ChammounC** [comment]
@Anandsg yes, I have been working with react for some time now. First, I would have to look into the codebase and then build a component for the toast message. Thinking of making the toast appear from the top when an item is added to cart.

**Comment by Anandsg** [comment]
> @Anandsg yes, I have been working with react for some time now. First, I would have to look into the codebase and then build a component for the toast message. Thinking of making the toast appear from the top when an item is added to cart.

okay!

**Comment by FL45H404** [comment]
Hey @Anandsg ,should I work on that??

**Comment by FavourtheDeveloper** [comment]
I would love to also work on this.

**Comment by FL45H404** [comment]
hey Anand I got the solution could you assign me 

https://github.com/Anandsg/Hungry-hero/assets/70277710/347f172c-1710-443a-9196-025eb88b4b74

**Comment by Anandsg** [comment]
feature is implemented
