### ISSUE TITLE
[Bug report] : Restaurant Card redirection issue

### ISSUE THREAD

**Issue by ChammounC** [Anandsg/Hungry-hero#86]
## Summary:
Clicking on the image of a restaurant card does not trigger any action, while clicking on the card redirects correctly.

## Description:
I encountered a usability issue while using the site related to the behavior of restaurant cards. Specifically, when clicking on the image of a restaurant card, no action is initiated. However, clicking anywhere else on the card correctly triggers the intended redirection behavior.

## Steps to Reproduce:

&emsp; 1. Open the site.
&emsp; 2. Navigate to the restaurant listings page.
&emsp; 3. Locate a restaurant card displaying relevant information.
&emsp; 4. Attempt to click on the image of the restaurant card.

## Expected Behavior:
Clicking on the image of the restaurant card should initiate the same action as clicking anywhere else on the card.

## Actual Behavior:
Clicking on the image of the restaurant card does not trigger any action. However, clicking anywhere else on the card functions as expected, redirecting the user to the intended destination.

## Attachments:
![Screenshot 2023-10-06 171617](https://github.com/Anandsg/Hungry-hero/assets/43007452/27e919e3-d804-460e-bc08-ff86c2e266cd)

**Comment by Anandsg** [comment]
@ChammounC  yes would you like to address it ? we have implemented a favourite functionality over the res images make sure it doesn't affect other functionality

**Comment by ChammounC** [comment]
@Anandsg yes sure. I'll make sure it doesn't affect other functionalities.

**Comment by Anandsg** [comment]
This feature has been deployed
