### ISSUE TITLE
[Bug report] : Accordion Not Collapsing When 'Hide' Button Clicked

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#9]
**Issue:** 
The accordion feature in the app is not working as expected. When a user clicks on "Hide," the content is not collapsing as it should.

**Expected Behaviour:**
When the "Hide" button is clicked, the corresponding content should collapse or hide, making it hidden from view.

**Additional Information:**
This issue occurs consistently and can be reproduced on multiple devices and browsers.
Please find attached screenshot.

<img width="1440" alt="Screenshot 2023-09-26 at 9 32 52 AM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/8e6fcfc4-ed7c-4d0f-9656-f6d5c1c9eb0b">

**Comment by ronisarkarexe** [comment]
@Anandsg Could you please assign me this task? I am really interested in working on it. under Hacktoberfest

**Comment by Anandsg** [comment]
@ronisarkarexe yes start working on it, Assigning the issue to you.

Make sure to install CORS extension in order to run the app in your local machine
https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigee
