### ISSUE TITLE
Enhance UX by letting user press "Enter" key to run the search instead of having to press the "Search" button

### ISSUE THREAD

**Issue by original-subbaman** [Anandsg/Hungry-hero#91]
Hi, I have a suggestion to improve the user experience of your web app.

**Issue:** Currently user has to explicitly press the "Search" button to initiate the search. That is one extra click + press "Tab" does not move the focus to the "Search" button.

**My Suggestion:** Improve the user experience by making the search work when the "Enter" key is pressed. Also moving the focus to "Search" button when "Tab" key is pressed. 

Would love your thoughts on this.

**Comment by Anandsg** [comment]
yes this make sense go for it @original-subbaman

**Comment by Anandsg** [comment]
feature has been implemented
