### ISSUE TITLE
Restaurent card overlap at specific width-range

### ISSUE THREAD

**Issue by Rahulj9a** [Anandsg/Hungry-hero#93]
Restaurant card are overlapping between 1020px - 1400px width. I guess the width shouldn't be hardcoded; I have already start to work on this issue. Pls. assign it to me.
![image](https://github.com/Anandsg/Hungry-hero/assets/101471306/f5311f8f-9b5d-4dab-9408-912dbdff34e5)

**Comment by Anandsg** [comment]
yeah this is happening on some specific systems @Rahulj9a please go for it.

**Comment by Rahulj9a** [comment]
Hey can you label my issue for hacktoberfest standards pls.

**Comment by Rahulj9a** [comment]
I have initiated PR for the same
