### ISSUE TITLE
Implement different colour for ratings less than 4 in restaurant cards

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#98]
**Current Behaviour:**

Currently, the restaurant cards display ratings in green, regardless of the actual rating value. This can be confusing for users who want to identify restaurants with ratings less than 4.

**Proposed Enhancement:**

I propose that we introduce a feature where restaurant cards display ratings in maroon or some suitable colours if the rating is less than 4. This visual cue will make it easier for users to identify restaurants with lower ratings.

**Additional details:**

We've attached a screenshot showcasing our vision for displaying ratings. Take a look at how we plan to implement the rating colour scheme
<img width="790" alt="Screenshot 2023-10-07 at 12 46 46 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/87fa5a1f-6a66-43ba-885d-20da69740962">

**Comment by du1ana** [comment]
Hi, I like to work on this implementation. Please assign it to me.

**Comment by prakhar1535** [comment]
i want to work on this issue please assign
